################################################################################
#                     Copyright @ 2012,2013 CloudDepot, Inc.                   #
#                               All Rights Reserved                            #
################################################################################

#======================================#
# Engine Settings
#======================================#

engine:
  license: p8GV-ppVp-p2Vp
  auth_key: 5F3BDD56
  sleep_interval: 5