################################################################################
#                     Copyright @ 2012,2013 CloudDepot, Inc.                   #
#                               All Rights Reserved                            #
################################################################################

#======================================#
# Worker Settings
#======================================#

worker:
  auth_key: 5F3BDD56
  port: 50000